/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
                    "inverse-surface": "#e5e1e4",
                    "on-surface": "#e5e1e4",
                    "secondary": "#c8c6c9",
                    "primary-fixed": "#d5f000",
                    "on-tertiary-fixed": "#1b1b21",
                    "surface-container": "#201f22",
                    "surface-container-highest": "#353437",
                    "surface-bright": "#39393b",
                    "inverse-on-surface": "#313032",
                    "secondary-fixed": "#e4e1e5",
                    "on-secondary": "#303033",
                    "on-background": "#e5e1e4",
                    "tertiary": "#ffffff",
                    "on-secondary-fixed-variant": "#47464a",
                    "error-container": "#93000a",
                    "on-primary-container": "#5e6b00",
                    "secondary-fixed-dim": "#c8c6c9",
                    "surface-dim": "#131315",
                    "outline": "#909378",
                    "surface-variant": "#353437",
                    "secondary-container": "#47464a",
                    "surface-tint": "#bbd200",
                    "primary-fixed-dim": "#bbd200",
                    "primary-container": "#d5f000",
                    "tertiary-container": "#e3e1ea",
                    "surface-container-high": "#2a2a2c",
                    "on-primary": "#2d3400",
                    "on-primary-fixed": "#191e00",
                    "on-primary-fixed-variant": "#424b00",
                    "surface-container-lowest": "#0e0e10",
                    "surface-container-low": "#1c1b1d",
                    "surface": "#131315",
                    "tertiary-fixed": "#e3e1ea",
                    "inverse-primary": "#586400",
                    "on-surface-variant": "#c7c9ab",
                    "on-error-container": "#ffdad6",
                    "error": "#ffb4ab",
                    "on-tertiary-container": "#64646b",
                    "on-secondary-fixed": "#1b1b1e",
                    "on-error": "#690005",
                    "primary": "#ffffff",
                    "on-secondary-container": "#b6b4b8",
                    "on-tertiary": "#303037",
                    "on-tertiary-fixed-variant": "#46464d",
                    "background": "#131315",
                    "outline-variant": "#464932",
                    "tertiary-fixed-dim": "#c7c5ce"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "gutter": "24px",
                    "base": "8px",
                    "margin-desktop": "48px",
                    "margin-mobile": "16px",
                    "container-max": "1280px"
            },
            "fontFamily": {
                    "body-md": ["Inter"],
                    "headline-xl": ["Inter"],
                    "display-lg-mobile": ["Inter"],
                    "body-lg": ["Inter"],
                    "label-md": ["Inter"],
                    "label-sm": ["Inter"],
                    "display-lg": ["Inter"],
                    "headline-lg": ["Inter"]
            },
            "fontSize": {
                    "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "headline-xl": ["36px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "display-lg-mobile": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "600"}],
                    "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-lg": ["28px", {"lineHeight": "1.3", "fontWeight": "600"}]
            }
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
}
